services:
  backend:
    container_name: backend
    image: back
    networks:
      backend_net:
        ipv4_address: 10.0.1.4
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always

  webApp:
    container_name: frontend
    image: front
    depends_on:
      - backend
    networks:
      backend_net:
        ipv4_address: 10.0.1.3
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"

networks:
  backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24